import pandas as pd

data = {
    "emails": [
        "Reactivate your account to continue services.",
        "Check out the slides from today\u2019s workshop.",
        "Meeting rescheduled to 3pm today.",
        "Limited time offer: Get your free iPhone now!",
        "Dinner plans still on for tonight?",
        "Meeting rescheduled to 3pm today.",
        "Unusual sign-in detected. Reset your password.",
        "Your credit score was checked recently. Review now.",
        "Check out the slides from today\u2019s workshop.",
        "Dinner plans still on for tonight?",
        "How was your vacation last week?",
        "Meeting rescheduled to 3pm today.",
        "Limited time offer: Get your free iPhone now!",
        "Join our fantasy league before Friday!",
        "Reset your password to continue using your account.",
        "Reset your password to continue using your account.",
        "Your PayPal account has been limited. Resolve now.",
        "Don\u2019t forget to RSVP for the wedding!",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "Your credit score was checked recently. Review now.",
        "Update your credentials or lose access.",
        "Immediate action required: unauthorized login attempt.",
        "Let\u2019s meet at the library at 2pm.",
        "Your credit score was checked recently. Review now.",
        "Join our fantasy league before Friday!",
        "You\u2019ve been selected to receive exclusive rewards.",
        "Happy birthday! Let\u2019s celebrate this weekend.",
        "Can you send me the notes from today's lecture?",
        "Verify your identity or your email will be locked.",
        "Verify your identity or your email will be locked.",
        "Here's the assignment template you requested.",
        "Click here to claim your refund now.",
        "Final warning: account will be deactivated.",
        "Your tax refund is pending. Click to claim.",
        "Don\u2019t forget to RSVP for the wedding!",
        "Meeting rescheduled to 3pm today.",
        "Join our fantasy league before Friday!",
        "Suspicious activity found in your bank account.",
        "Your tax refund is pending. Click to claim.",
        "Suspicious activity found in your bank account.",
        "Check out the slides from today\u2019s workshop.",
        "Class has been moved to Room 203.",
        "Sending over the project files now.",
        "Can you help me debug this code?",
        "Meeting rescheduled to 3pm today.",
        "Limited time offer: Get your free iPhone now!",
        "Happy birthday! Let\u2019s celebrate this weekend.",
        "Congrats on your internship offer!",
        "Class has been moved to Room 203.",
        "Your tax refund is pending. Click to claim.",
        "Your credit score was checked recently. Review now.",
        "How was your vacation last week?",
        "Reset your password to continue using your account.",
        "Your account has been compromised. Click here to secure it.",
        "Join our fantasy league before Friday!",
        "Class has been moved to Room 203.",
        "Meeting rescheduled to 3pm today.",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "Your credit score was checked recently. Review now.",
        "Immediate action required: unauthorized login attempt.",
        "Your PayPal account has been limited. Resolve now.",
        "Let\u2019s meet at the library at 2pm.",
        "Study group meets at 6pm in the lounge.",
        "Want to grab coffee before class?",
        "Download your invoice from the secure link.",
        "Your account has been compromised. Click here to secure it.",
        "Study group meets at 6pm in the lounge.",
        "Can you help me debug this code?",
        "Suspicious activity found in your bank account.",
        "Study group meets at 6pm in the lounge.",
        "Reactivate your account to continue services.",
        "Are you coming to the game tonight?",
        "Are you coming to the game tonight?",
        "Class has been moved to Room 203.",
        "Check out the slides from today\u2019s workshop.",
        "You\u2019ve been selected to receive exclusive rewards.",
        "How was your vacation last week?",
        "Happy birthday! Let\u2019s celebrate this weekend.",
        "Sending over the project files now.",
        "Sending over the project files now.",
        "Dinner plans still on for tonight?",
        "Can you help me debug this code?",
        "Limited time offer: Get your free iPhone now!",
        "Class has been moved to Room 203.",
        "Update your credentials or lose access.",
        "Congrats on your internship offer!",
        "Looking forward to the weekend getaway!",
        "Can you send me the notes from today's lecture?",
        "Your credit score was checked recently. Review now.",
        "Reset your password to continue using your account.",
        "Don\u2019t forget to RSVP for the wedding!",
        "Don\u2019t forget to RSVP for the wedding!",
        "Click here to claim your refund now.",
        "Your tax refund is pending. Click to claim.",
        "Congrats on your internship offer!",
        "Are you coming to the game tonight?",
        "How was your vacation last week?",
        "Team lunch at Olive Garden tomorrow?",
        "Are you coming to the game tonight?",
        "New document shared with you. Click to open.",
        "Congrats on your internship offer!",
        "Your credit score was checked recently. Review now.",
        "Study group meets at 6pm in the lounge.",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "Join our fantasy league before Friday!",
        "Study group meets at 6pm in the lounge.",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "Can you send me the notes from today's lecture?",
        "Want to grab coffee before class?",
        "New document shared with you. Click to open.",
        "Can you send me the notes from today's lecture?",
        "You\u2019ve been selected to receive exclusive rewards.",
        "Click here to claim your refund now.",
        "Can you help me debug this code?",
        "Can you help me debug this code?",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "Check out the slides from today\u2019s workshop.",
        "How was your vacation last week?",
        "Verify your identity or your email will be locked.",
        "Dinner plans still on for tonight?",
        "Warning: Your mailbox is almost full. Act now!",
        "Sending over the project files now.",
        "Warning: Your mailbox is almost full. Act now!",
        "Limited time offer: Get your free iPhone now!",
        "Don\u2019t forget to RSVP for the wedding!",
        "Dinner plans still on for tonight?",
        "Unusual sign-in detected. Reset your password.",
        "Can you send me the notes from today's lecture?",
        "Dinner plans still on for tonight?",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "Class has been moved to Room 203.",
        "Can you send me the notes from today's lecture?",
        "Your tax refund is pending. Click to claim.",
        "Your credit score was checked recently. Review now.",
        "Limited time offer: Get your free iPhone now!",
        "Dinner plans still on for tonight?",
        "Reset your password to continue using your account.",
        "Verify your identity or your email will be locked.",
        "Confirm your billing info to avoid service interruption.",
        "Meeting rescheduled to 3pm today.",
        "Don\u2019t forget to RSVP for the wedding!",
        "Immediate action required: unauthorized login attempt.",
        "Looking forward to the weekend getaway!",
        "You\u2019ve been selected to receive exclusive rewards.",
        "Check out the slides from today\u2019s workshop.",
        "Your account has been compromised. Click here to secure it.",
        "Class has been moved to Room 203.",
        "Unusual sign-in detected. Reset your password.",
        "Dinner plans still on for tonight?",
        "Dinner plans still on for tonight?",
        "Limited time offer: Get your free iPhone now!",
        "Limited time offer: Get your free iPhone now!",
        "Your tax refund is pending. Click to claim.",
        "Join our fantasy league before Friday!",
        "New document shared with you. Click to open.",
        "Class has been moved to Room 203.",
        "Check out the slides from today\u2019s workshop.",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "Your credit score was checked recently. Review now.",
        "Verify your identity or your email will be locked.",
        "Check out the slides from today\u2019s workshop.",
        "Download your invoice from the secure link.",
        "Study group meets at 6pm in the lounge.",
        "Don\u2019t forget to RSVP for the wedding!",
        "Dinner plans still on for tonight?",
        "Don\u2019t forget to RSVP for the wedding!",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "Happy birthday! Let\u2019s celebrate this weekend.",
        "How was your vacation last week?",
        "Warning: Your mailbox is almost full. Act now!",
        "Reset your password to continue using your account.",
        "Sending over the project files now.",
        "Verify your identity or your email will be locked.",
        "Update your credentials or lose access.",
        "Reset your password to continue using your account.",
        "Confirm your billing info to avoid service interruption.",
        "Update your credentials or lose access.",
        "Warning: Your mailbox is almost full. Act now!",
        "Verify your identity or your email will be locked.",
        "Sending over the project files now.",
        "Suspicious activity found in your bank account.",
        "Reset your password to continue using your account.",
        "Movie night this Friday at my place?",
        "Unusual sign-in detected. Reset your password.",
        "Reactivate your account to continue services.",
        "Unusual sign-in detected. Reset your password.",
        "Want to grab coffee before class?",
        "Your credit score was checked recently. Review now.",
        "Congrats on your internship offer!",
        "Your PayPal account has been limited. Resolve now.",
        "Reactivate your account to continue services.",
        "New document shared with you. Click to open.",
        "Don\u2019t forget to RSVP for the wedding!",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "You\u2019ve been selected to receive exclusive rewards.",
        "Dinner plans still on for tonight?",
        "Movie night this Friday at my place?",
        "Here's the assignment template you requested.",
        "Looking forward to the weekend getaway!",
        "Your PayPal account has been limited. Resolve now.",
        "Immediate action required: unauthorized login attempt.",
        "Confirm your billing info to avoid service interruption.",
        "Team lunch at Olive Garden tomorrow?",
        "Your PayPal account has been limited. Resolve now.",
        "Join our fantasy league before Friday!",
        "Dinner plans still on for tonight?",
        "Let\u2019s meet at the library at 2pm.",
        "Reset your password to continue using your account.",
        "Movie night this Friday at my place?",
        "Class has been moved to Room 203.",
        "Warning: Your mailbox is almost full. Act now!",
        "Study group meets at 6pm in the lounge.",
        "Limited time offer: Get your free iPhone now!",
        "Your account has been compromised. Click here to secure it.",
        "Verify your identity or your email will be locked.",
        "Reset your password to continue using your account.",
        "Click here to claim your refund now.",
        "Happy birthday! Let\u2019s celebrate this weekend.",
        "Your account has been compromised. Click here to secure it.",
        "Download your invoice from the secure link.",
        "Sending over the project files now.",
        "New document shared with you. Click to open.",
        "Final warning: account will be deactivated.",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "Class has been moved to Room 203.",
        "Join our fantasy league before Friday!",
        "Join our fantasy league before Friday!",
        "Can you help me debug this code?",
        "Immediate action required: unauthorized login attempt.",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "Dinner plans still on for tonight?",
        "Your PayPal account has been limited. Resolve now.",
        "How was your vacation last week?",
        "New document shared with you. Click to open.",
        "Reactivate your account to continue services.",
        "Your account has been compromised. Click here to secure it.",
        "Class has been moved to Room 203.",
        "Immediate action required: unauthorized login attempt.",
        "Click here to claim your refund now.",
        "New document shared with you. Click to open.",
        "Study group meets at 6pm in the lounge.",
        "Your account has been compromised. Click here to secure it.",
        "Update your credentials or lose access.",
        "Can you help me debug this code?",
        "Verify your identity or your email will be locked.",
        "Immediate action required: unauthorized login attempt.",
        "Click here to claim your refund now.",
        "Meeting rescheduled to 3pm today.",
        "You\u2019ve been selected to receive exclusive rewards.",
        "Dinner plans still on for tonight?",
        "Immediate action required: unauthorized login attempt.",
        "Suspicious activity found in your bank account.",
        "Check out the slides from today\u2019s workshop.",
        "Immediate action required: unauthorized login attempt.",
        "Here's the assignment template you requested.",
        "Don\u2019t forget to RSVP for the wedding!",
        "New document shared with you. Click to open.",
        "Download your invoice from the secure link.",
        "Don\u2019t forget to RSVP for the wedding!",
        "Movie night this Friday at my place?",
        "Want to grab coffee before class?",
        "Download your invoice from the secure link.",
        "Verify your identity or your email will be locked.",
        "Looking forward to the weekend getaway!",
        "Looking forward to the weekend getaway!",
        "Looking forward to the weekend getaway!",
        "Meeting rescheduled to 3pm today.",
        "Reset your password to continue using your account.",
        "Congratulations! You've won a $1000 Walmart gift card.",
        "Immediate action required: unauthorized login attempt.",
        "Join our fantasy league before Friday!",
        "Looking forward to the weekend getaway!",
        "Unusual sign-in detected. Reset your password.",
        "Your tax refund is pending. Click to claim.",
        "Your account has been compromised. Click here to secure it.",
        "How was your vacation last week?",
        "Download your invoice from the secure link.",
        "Final warning: account will be deactivated.",
        "Study group meets at 6pm in the lounge.",
        "Your account has been compromised. Click here to secure it.",
        "Click here to claim your refund now.",
        "Study group meets at 6pm in the lounge.",
        "Congrats on your internship offer!",
        "Sending over the project files now.",
        "Class has been moved to Room 203.",
        "Here's the assignment template you requested.",
        "Check out the slides from today\u2019s workshop.",
        "Are you coming to the game tonight?",
        "Verify your identity or your email will be locked.",
        "Final warning: account will be deactivated.",
        "You\u2019ve been selected to receive exclusive rewards.",
        "How was your vacation last week?",
        "Reactivate your account to continue services.",
        "Sending over the project files now.",
        "Your tax refund is pending. Click to claim.",
        "Class has been moved to Room 203.",
        "Reset your password to continue using your account.",
        "New document shared with you. Click to open.",
        "How was your vacation last week?",
        "Happy birthday! Let\u2019s celebrate this weekend."
    ],
    "labels": [
        "phishing",
        "legit",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "legit",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "legit",
        "legit",
        "legit",
        "phishing",
        "legit",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "legit",
        "legit",
        "legit",
        "phishing",
        "legit",
        "legit",
        "legit",
        "legit",
        "legit",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "legit",
        "legit",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "legit",
        "legit",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "phishing",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "legit",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit",
        "legit",
        "legit",
        "legit",
        "legit",
        "legit",
        "phishing",
        "phishing",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "legit",
        "phishing",
        "phishing",
        "legit",
        "legit"
    ]
}




from sklearn.feature_extraction.text import TfidfVectorizer

vector = TfidfVectorizer(ngram_range=(1, 2))
vectors = vector.fit_transform(data["emails"])
print("TF-IDF Matrix shape:", vectors.shape)
print("Words used (features):", vector.get_feature_names_out())




def extract_custom_features(email):
    return {
        "has_link": int("http" in email or ".com" in email),
        "exclamations": email.count("!"),
        "all_caps": sum(1 for word in email.split() if word.isupper())
    }

# Extract custom features
custom_features = [extract_custom_features(email) for email in data["emails"]]
custom_df = pd.DataFrame(custom_features)


from scipy.sparse import hstack

# Convert custom features to NumPy array
custom_array = custom_df.to_numpy()

# Combine sparse TF-IDF matrix with dense custom features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
custom_scaled = scaler.fit_transform(custom_array)

# Final features
from scipy.sparse import csr_matrix
final_vectors = hstack([vectors, csr_matrix(custom_scaled)])



from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Split the data into training and testing parts
X_train, X_test, Y_train, Y_test = train_test_split(final_vectors, data["labels"], test_size=0.4, random_state=42, shuffle = True)

# Create the robot brain (model)
model = LogisticRegression()

# Teach the robot using the training data
model.fit(X_train, Y_train)



from sklearn.metrics import accuracy_score, classification_report

# Step 1: Use the model to predict on the test set
y_pred = model.predict(X_test)

# Step 2: Compare predictions with actual answers
print("Accuracy:", accuracy_score(Y_test, y_pred))

# Step 3: See detailed results
print("\nClassification Report:\n", classification_report(Y_test, y_pred))

new_email = input("Paste an email here: ")
new_email_vector = vector.transform([new_email])

# Extract custom features for the new email
new_email_custom_features = extract_custom_features(new_email)
new_email_custom_df = pd.DataFrame([new_email_custom_features]) # Convert to DataFrame
new_email_custom_array = new_email_custom_df.to_numpy() # Convert to NumPy array
new_email_custom_scaled = scaler.transform(new_email_custom_array) # Scale using the existing scaler

# Combine TF-IDF vector and custom features for the new email
new_email_final_vectors = hstack([new_email_vector, csr_matrix(new_email_custom_scaled)])

# Now you can use 'new_email_final_vectors' for prediction
prediction = model.predict(new_email_final_vectors)
print("Prediction:", prediction)
